version: '3'

services:
  app:
    build: ./backend
    restart: always
    ports:
      - ${PORT}:${PORT}
    networks:
      - app_net
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI_COMPOSE: mongodb://${MONGO_HOST}:${MONGO_PASSWORD}@mongo:27017/

  mongo:
    image: mongo
    restart: always
    networks:
      - app_net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_HOST}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - app_net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_HOST}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_HOST}:${MONGO_PASSWORD}@mongo:27017/

networks:
  app_net:
    driver: bridge